# Site settings
title: AI for Content Creation Workshop
email: contact@ai4cc.net
description: >- # This means to ignore newlines until "baseurl:"
  Webpage for the AI for Content Creation workshop hosted at CVPR.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ai4cc.net/" # the base hostname & protocol for your site, e.g. http://example.com